import { Recipe, type PlanStep } from '@outskirts/schemas';

export const INSPECTION_APPROVAL_RECIPE: Recipe = Recipe.parse({
  recipeId: 'inspection-report-to-approval-note',
  version: '1.0.0',
  title: 'Refinery Inspection Report to Signed Approval Note',
  description:
    'Eight-stage industrial workflow: document intake, finding extraction, hydraulic/thickness calculation, SOP retrieval with freshness scoring, draft synthesis, deterministic critic verification (C1-C5), C2PA-signed deliverable, and Decision DNA attestation.',
  matches: [
    'inspection report to approval note',
    'pressure vessel inspection',
    'piping inspection approval',
    'thickness corrosion approval note',
  ],
  parameters: [
    {
      name: 'reportPath',
      schemaRef: 'SchemaRef',
      required: true,
      description: 'Path or identifier of the scanned inspection report',
    },
  ],
  steps: [
    {
      stepId: 'step-1-intake',
      kind: 'document',
      description: 'Acquire and parse inspection scan metadata and structure',
      dependsOn: [],
      plugins: [],
      status: 'pending',
    },
    {
      stepId: 'step-2-extract',
      kind: 'document',
      description: 'Extract thickness measurements, corrosion rates, and operational parameters',
      dependsOn: ['step-1-intake'],
      plugins: [],
      outputSchemaRef: 'InspectionExtraction',
      status: 'pending',
    },
    {
      stepId: 'step-3-calc',
      kind: 'calculation',
      description: 'Execute Darcy-Weisbach frictional pressure drop verification via engineering plugin',
      dependsOn: ['step-2-extract'],
      plugins: ['pipe-calc-plugin'],
      outputSchemaRef: 'CalcResult',
      status: 'pending',
    },
    {
      stepId: 'step-4-retrieve',
      kind: 'retrieve',
      description: 'Retrieve governing refinery standards and SOPs with freshness decay scoring',
      dependsOn: ['step-2-extract'],
      plugins: [],
      outputSchemaRef: 'Citation',
      status: 'pending',
    },
    {
      stepId: 'step-5-draft',
      kind: 'document',
      description: 'Synthesize formal approval note integrating findings, calculations, and governing citations',
      dependsOn: ['step-3-calc', 'step-4-retrieve'],
      plugins: [],
      status: 'pending',
    },
    {
      stepId: 'step-6-critic',
      kind: 'document',
      description: 'Execute deterministic critic verification (C1 numeric grounding, C2 calc replay, C3 citation overlap, C4 completeness, C5 freshness policy)',
      dependsOn: ['step-5-draft'],
      plugins: [],
      outputSchemaRef: 'CriticVerdict',
      status: 'pending',
    },
    {
      stepId: 'step-7-deliver',
      kind: 'document',
      description: 'Render deliverable document (.docx) and generate C2PA manifest with content hash binding',
      dependsOn: ['step-6-critic'],
      plugins: [],
      status: 'pending',
    },
    {
      stepId: 'step-8-record',
      kind: 'document',
      description: 'Project Decision DNA record, in-toto link attestations, and commit signed audit anchor',
      dependsOn: ['step-7-deliver'],
      plugins: [],
      outputSchemaRef: 'DecisionDna',
      status: 'pending',
    },
  ],
});
